bot:
  # 反向ws地址
  HOST : 127.0.0.1
  # 端口
  PORT : 5700
  # debug模式
  DEBUG : true
  # 超级用户列表
  SUPERUSERS : [1007928648]
  # 昵称
  NICKNAME : [Dorothy, dorothy]
  # 命令标识头
  COMMAND_START : ["", "/"]
  #命令分离符号
  COMMAND_SEP : ["."]

hefeng:
  SEARCH_API: https://geoapi.qweather.com/v2/city/lookup?
  WEATHER_NOW_API: https://devapi.qweather.com/v7/weather/now?
  AIR_NOW_API: https://devapi.qweather.com/v7/air/now?
  KEY: 50bf6718eee8448f991f89f423e63afb
  HWY: 222
