bot:
  # 反向ws地址
  HOST : 127.0.0.1
  # 端口
  PORT : 5700
  # debug模式
  DEBUG : true
  # 超级用户列表
  SUPERUSERS : [1007928648]
  # 昵称
  NICKNAME : [Dorothy, dorothy]
  # 命令标识头
  COMMAND_START : ["", "/"]
  #命令分离符号
  COMMAND_SEP : ["."]

hefeng:
  SEARCH_API: https://geoapi.qweather.com/v2/city/lookup?
  WEATHER_NOW_API: https://devapi.qweather.com/v7/weather/now?
  AIR_NOW_API: https://devapi.qweather.com/v7/air/now?
  KEY: 50bf6718eee8448f991f89f423e63afb

setu:
  API: https://api.lolicon.app/setu/
  KEY: 865284495fd02aa8db6371

saucenao:
  API: https://saucenao.com/search.php
  KEY: 736ddb6c1be2f6b4aafd158177d862c78eb310ce

shadiao:
  zui_chou: https://nmsl.shadiao.app/api.php?level=min&lang=zh_cn
  peng_you_quan: https://pyq.shadiao.app/api.php
  rainbow_fart: https://chp.shadiao.app/api.php
  du_ji_tang: https://du.shadiao.app/api.php
  nbnhhsh: https://lab.magiconch.com/api/nbnhhsh/guess

ad_api:
  hitokoto: https://api.imjad.cn/hitokoto/
  cloud_music: https://api.imjad.cn/cloudmusic/